apiVersion: v1
kind: List
items:
  - metadata:
      labels:
        app: weave-flux
        name: weave-flux-agent
        weave-cloud-component: flux
        weave-flux-component: agent
      name: weave-flux-agent
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "server-version": "master-1072121",
            "original-request": {
              "url": "/k8s.yaml?t=REDACTED&weave-scope-version=1.1.0",
              "date": "Fri Feb 03 2017 16:38:55 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
    spec:
      template:
        metadata:
          labels:
            app: weave-flux
            name: weave-flux-agent
            weave-cloud-component: flux
            weave-flux-component: agent
        spec:
          containers:
            - name: agent
              image: 'quay.io/weaveworks/fluxd:0.1.0'
              imagePullPolicy: IfNotPresent
              args:
                - '--token={{.Values.ServiceToken}}'
      replicas: 1
    apiVersion: extensions/v1beta1
    kind: Deployment
  - metadata:
      labels:
        app: weave-scope
        name: weave-scope-agent
        weave-cloud-component: scope
        weave-scope-component: agent
      name: weave-scope-agent
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "server-version": "master-1072121",
            "original-request": {
              "url": "/k8s.yaml?t=REDACTED&weave-scope-version=1.1.0",
              "date": "Fri Feb 03 2017 16:38:55 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
    spec:
      template:
        metadata:
          labels:
            app: weave-scope
            name: weave-scope-agent
            weave-cloud-component: scope
            weave-scope-component: agent
        spec:
          containers:
            - name: agent
              image: 'weaveworks/scope:latest'
              imagePullPolicy: IfNotPresent
              args:
                - '--no-app'
                - '--probe.docker.bridge=docker0'
                - '--probe.docker=true'
                - '--probe.kubernetes=true'
                - '--service-token={{.Values.ServiceToken}}'
              securityContext:
                privileged: true
              volumeMounts:
                - name: docker-socket
                  mountPath: /var/run/docker.sock
                - name: scope-plugins
                  mountPath: /var/run/scope/plugins
          volumes:
            - name: docker-socket
              hostPath:
                path: /var/run/docker.sock
            - name: scope-plugins
              hostPath:
                path: /var/run/scope/plugins
          hostPID: true
          hostNetwork: true
    apiVersion: extensions/v1beta1
    kind: DaemonSet
  - metadata:
      labels:
        app: weave-cortex
        name: weave-cortex-agent
        weave-cloud-component: cortex
        weave-cortex-component: agent
      name: weave-cortex-agent
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "server-version": "master-1072121",
            "original-request": {
              "url": "/k8s.yaml?t=REDACTED&weave-scope-version=1.1.0",
              "date": "Fri Feb 03 2017 16:38:55 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
    spec:
      template:
        metadata:
          labels:
            app: weave-cortex
            name: weave-cortex-agent
            weave-cloud-component: cortex
            weave-cortex-component: agent
        spec:
          containers:
            - name: agent
              image: 'prom/prometheus:v1.3.1'
              imagePullPolicy: IfNotPresent
              args:
                - '-config.file=/etc/prometheus/prometheus.yml'
                - '-web.listen-address=:80'
              ports:
                - containerPort: 80
                  protocol: TCP
              volumeMounts:
                - name: agent-config-volume
                  mountPath: /etc/prometheus
          volumes:
            - name: agent-config-volume
              configMap:
                name: weave-cortex-agent-config
      replicas: 1
    apiVersion: extensions/v1beta1
    kind: Deployment
  - metadata:
      labels:
        app: weave-cortex
        name: weave-cortex-agent-config
        weave-cloud-component: cortex
        weave-cortex-component: agent-config
      name: weave-cortex-agent-config
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "server-version": "master-1072121",
            "original-request": {
              "url": "/k8s.yaml?t=REDACTED&weave-scope-version=1.1.0",
              "date": "Fri Feb 03 2017 16:38:55 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
    data:
      prometheus.yml: |
        global:
          scrape_interval: 15s
        remote_write:
          url: 'https://cloud.weave.works/api/prom/push'
          basic_auth:
            password: '{{.Values.ServiceToken}}'
        scrape_configs:
          - job_name: kubernetes-service-endpoints
            kubernetes_sd_configs:
              - role: endpoints
            tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            relabel_configs:
              - source_labels:
                  - __meta_kubernetes_service_label_component
                regex: apiserver
                action: replace
                target_label: __scheme__
                replacement: https
              - source_labels:
                  - __meta_kubernetes_service_label_kubernetes_io_cluster_service
                action: drop
                regex: 'true'
              - source_labels:
                  - __meta_kubernetes_service_annotation_prometheus_io_scrape
                action: drop
                regex: 'false'
              - source_labels:
                  - __meta_kubernetes_pod_container_port_name
                action: drop
                regex: .*-noscrape
              - source_labels:
                  - __meta_kubernetes_service_annotation_prometheus_io_scheme
                action: replace
                target_label: __scheme__
                regex: ^(https?)$
                replacement: $1
              - source_labels:
                  - __meta_kubernetes_service_annotation_prometheus_io_path
                action: replace
                target_label: __metrics_path__
                regex: ^(.+)$
                replacement: $1
              - source_labels:
                  - __address__
                  - __meta_kubernetes_service_annotation_prometheus_io_port
                action: replace
                target_label: __address__
                regex: '^(.+)(?::\d+);(\d+)$'
                replacement: '$1:$2'
              - action: labelmap
                regex: ^__meta_kubernetes_service_label_(.+)$
                replacement: $1
              - source_labels:
                  - __meta_kubernetes_namespace
                  - __meta_kubernetes_service_name
                separator: /
                target_label: job
          - job_name: kubernetes-pods
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels:
                  - __meta_kubernetes_pod_annotation_prometheus_io_scrape
                action: keep
                regex: 'true'
              - source_labels:
                  - __meta_kubernetes_namespace
                  - __meta_kubernetes_pod_label_name
                separator: /
                target_label: job
              - source_labels:
                  - __meta_kubernetes_pod_node_name
                target_label: node
          - job_name: kubernetes-nodes
            kubernetes_sd_configs:
              - role: node
            tls_config:
              insecure_skip_verify: true
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            relabel_configs:
              - target_label: __scheme__
                replacement: https
              - source_labels:
                  - __meta_kubernetes_node_label_kubernetes_io_hostname
                target_label: instance
          - job_name: weave
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels:
                  - __meta_kubernetes_namespace
                  - __meta_kubernetes_pod_label_name
                action: keep
                regex: ^kube-system;weave-net$
              - source_labels:
                  - __meta_kubernetes_pod_container_name
                  - __address__
                action: replace
                target_label: __address__
                regex: '^weave;(.+?)(?::\d+)?$'
                replacement: '$1:6782'
              - source_labels:
                  - __meta_kubernetes_pod_container_name
                  - __address__
                action: replace
                target_label: __address__
                regex: '^weave-npc;(.+?)(?::\d+)?$'
                replacement: '$1:6781'
              - source_labels:
                  - __meta_kubernetes_pod_container_name
                action: replace
                target_label: job
    apiVersion: v1
    kind: ConfigMap
  - metadata:
      labels:
        app: weave-cortex
        name: weave-cortex-agent
        weave-cloud-component: cortex
        weave-cortex-component: agent
      name: weave-cortex-agent
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "server-version": "master-1072121",
            "original-request": {
              "url": "/k8s.yaml?t=REDACTED&weave-scope-version=1.1.0",
              "date": "Fri Feb 03 2017 16:38:55 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
    spec:
      ports:
        - name: agent
          port: 80
          targetPort: 80
          protocol: TCP
      selector:
        app: weave-cortex
        name: weave-cortex-agent
        weave-cloud-component: cortex
        weave-cortex-component: agent
    apiVersion: v1
    kind: Service
  - spec:
      template:
        metadata:
          annotations:
            prometheus.io.scrape: 'true'
          labels:
            app: weave-cortex
            name: weave-cortex-node-exporter
            weave-cloud-component: cortex
            weave-cortex-component: node-exporter
        spec:
          containers:
            - name: agent
              image: 'prom/node-exporter:0.12.0'
              imagePullPolicy: IfNotPresent
              securityContext:
                privileged: true
              ports:
                - containerPort: 9100
                  protocol: TCP
          hostPID: true
          hostNetwork: true
    metadata:
      labels:
        app: weave-cortex
        name: weave-cortex-node-exporter
        weave-cloud-component: cortex
        weave-cortex-component: node-exporter
      name: weave-cortex-node-exporter
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "server-version": "master-1072121",
            "original-request": {
              "url": "/k8s.yaml?t=REDACTED&weave-scope-version=1.1.0",
              "date": "Fri Feb 03 2017 16:38:55 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
    apiVersion: extensions/v1beta1
    kind: DaemonSet
