#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

## To be sure, this won't work in your fork :)
## Surelly it's secure already, but we want to avoid any silly
## errors in your fork's build output.
test "${TRAVIS_REPO_SLUG}" = 'errordeveloper/kubegen' || exit 1

## # This is the shape of unencrypted `/tmp/release-secrets.sh`
##
## readonly signing_key='/tmp/equinox.key'
##
## cat > '/tmp/equinox.key' << EOF
## -----BEGIN ECDSA PRIVATE KEY-----
## <...>
## -----END ECDSA PRIVATE KEY-----
## EOF
## readonly app='...'
## readonly token='...'
##
## # To update, edit local copy of `release-secrets.sh` and run
## travis encrypt-file -r errordeveloper/kubegen release-secrets.sh
## cat release-secrets.sh.enc | base64 -b 64 | pbcopy
## # Next, copy the output down below and update `.travis.yml`

readonly secrets='/tmp/release-secrets.sh'
openssl base64 -d << EOF \
  | openssl aes-256-cbc -d -K "${1}" -iv "${2}" \
    -out "${secrets}"
l3RPTYRyenkmXwXWx/Kv9jJq6pME2lBO34OALkAgx2aG1Gp1PV+/1FWKKEHaTIPC
RDcXVJzQECm82wUtALMuQGGgCjUJAhSY9U2GWfiL2FqTxzatb99WzeVt9MUyxsSw
P+CkDymYgtS8LrBMflX2lbGTTj0BqByYc6j1nE0R9Nv2oJ5AI/AT26aog+xWkLY3
cWy4KqiKl8ANP0YIJ+wO+SDN0YZLvPQ/PeAy6Ec2Ox//5Hf/9kL2R/b3D3Mcjsf0
5/xZoM8yxj1+NftqRVPs7EYCUkUkEqOXPmlZSeDTWGpR/pbWe34C6BBPTxWcPzvZ
pdtLyRKpMMKzcYfBBddKqw/NyCJqC9mDnkiud0do5RVyGom1YvWuf3/s935wht8G
155QbEBfnjEUoq3aaR7xl3yyA+4a2hVTCcNYJt3UhNToesVK86yJKFSoLxgWr5oT
aHTdrm6x1CTiIYxzepVJgP7SousZqEGnhfEyvUWdsRGhIWw8TZ2rHAe/JZyo1R/o
C8hH2MQOqX7H+gB+uoVH/8tH/Geuh9UNjsgC5//vGhRj0P9alxs+sKAICjEXZMep
DAcDJVnZZn9TqjBxsK3u13QEe/Vg9ySczVlN2ruAJhjgXdfn0Ti4aw7dXJPsK8B5
EOF

source "${secrets}"

version="${TRAVIS_BRANCH}-${TRAVIS_COMMIT:0:8}"
channel='latest'

if [ -n "${TRAVIS_TAG}" ]; then
  ## Travis will run separate build for commit and tag pushes,
  version="${TRAVIS_TAG}"
  channel='stable'
fi

export CGO_ENABLED=0

case "${TRAVIS_OS_NAME}" in
  osx)
    exit 0
    ;;
  linux)
    readonly platforms='linux_amd64 darwin_amd64'
    readonly equinox='https://bin.equinox.io/c/mBWdkfai63v/release-tool-stable-linux-amd64.tgz'
    ;;
esac

curl --silent --location "${equinox}" | tar -zx

./equinox release \
  --platforms="${platforms}" \
  --app="${app}" \
  --token="${token}" \
  --signing-key="${signing_key}" \
  --channel="${channel}" \
  --version="${version}" \
    'github.com/errordeveloper/kubegen/cmd/kubegen'

rm -f "${secrets}" "${signing_key}"
