#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

## To be sure, this won't work in your fork :)
## Surelly it's secure already, but we want to avoid any silly
## errors in your fork's build output.
test "${TRAVIS_REPO_SLUG}" = 'errordeveloper/kubegen' || exit 1

## # This is the shape of unencrypted `/tmp/release-secrets.sh`
##
## readonly signing_key='/tmp/equinox.key'
##
## cat > '/tmp/equinox.key' << EOF
## -----BEGIN ECDSA PRIVATE KEY-----
## <...>
## -----END ECDSA PRIVATE KEY-----
## EOF
## readonly app='...'
## readonly token='...'
##
## # To update, edit local copy of `release-secrets.sh` and run
## travis encrypt-file -r errordeveloper/kubegen release-secrets.sh
## cat release-secrets.sh.enc | base64 -b 64
## # Next, copy the output down below and update `.travis.yml`

readonly secrets='/tmp/release-secrets.sh'
openssl base64 -d << EOF \
  | openssl aes-256-cbc -d -K "${1}" -iv "${2}" \
    -out "${secrets}"
DfTZCnjSRE5+b2o4B4ZDGKJDY5MQF7auWNEkLWzLbT+QALaSJ5hk7dlGQWSgw8Iy
ZC2MGwrYogUBBEhG2VkjopHQ82xc90scRgryYQpOgKYB8CCpJMiYapTJ/z1ABxTE
wauJVov+LjOycB9wA/ZDio1ldkyqBSSvBGDQxoi/eRe+EB37q8ky/L0vD6e4kJnH
fjKWLv+/L8Z//kkbyafFaMMZziO+AKlpn/kODwTUAUOdlGhxDfqrcTkkZZ9Q/0Qk
OuBQ7gsPGWvCnGz8PM4H50ViNRv7HNuJRo5VZ1Lu/eePP/GN6IefNe9qAoJngP43
zYe2L8L0RqGnBFSfatW07xohWsSHyVLkSsHqBEQ1EBSGSHcwWJd/ftx5q6nrn+KE
O9h85Hj1x11oajXs0ri2BMmBARM7FsM/F4RMduzJMNS0mIyMZ6zmZN2eFQv5LLy0
NjvSZR8Dl5737je9v0pAKrmWOv9mWHcfuRNkXMS2gRse5hrG9AHfNnPy+6equQgl
Pn+Ux5tYEE0bOWtDJSIQR83mLupiMaKyCMxeYqzA7Gk14R0rZvssjsdXBDRWbNVn
8Z7aBu5efkN7xo3s9uLcqOHbiUWC0JF9UI9vpWeTqAaspAlIYe53wQUxhLslMmfT
EOF

source "${secrets}"

version="${TRAVIS_BRANCH}-${TRAVIS_COMMIT:8}"
channel='latest'

if [ -n "${TRAVIS_TAG}" ]; then
  ## Travis will run separate build for commit and tag pushes,
  version="${TRAVIS_TAG}"
  channel='stable'
fi

export CGO_ENABLED=0

case "${TRAVIS_OS_NAME}" in
  osx)
    exit 0
    ;;
  linux)
    readonly platforms='linux_amd64 darwin_amd64'
    readonly equinox='https://bin.equinox.io/c/mBWdkfai63v/release-tool-stable-linux-amd64.tgz'
    ;;
esac

curl --silent --location "${equinox}" | tar -vzx

./equinox release \
  --platforms="${platforms}" \
  --app="${app}" \
  --token="${token}" \
  --signing-key="${signing_key}" \
  --channel="${channel}" \
  --version="${version}" \
    'github.com/errordeveloper/kubegen/cmd/kubegen'

rm -f "${secrets}" "${signing_key}"
